spring:
  application:
    name: eureka-server

server:
  port: 8802

eureka:
  instance:
    #    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8800/eureka/,http://127.0.0.1:8802/eureka/



