feign:
  hystrix:
    enabled: true #开启断路器才能生效

management:
  endpoints:
    web:
      exposure:
        include: refresh,health
        #暴露能被访问的地址：配置刷新（curl -X POST http://localhost:8802/actuator/refresh）和健康检查

config:
  test: public-dev